import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useBundleQuery } from "@/hooks/useBundleQuery";
import { useProductQuery } from "@/hooks/useProductQuery";
import { Card } from "@/components/Card";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { bundles } = useBundleQuery();
  //birchwood-breeze-deodorant
  const { product } = useProductQuery("birchwood-breeze-deodorant");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {bundles.map((bundle, i) => (
          <Card bundle={bundle} key={i} />
        ))}

        {product && product.price}
      </main>
    </>
  );
}
